
fullnameOverride: "home"

replicaCount: 1

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: home-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: home
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    env:
      CYBER_DOJO_PROMETHEUS: "true"
    volumeMounts:
      - name: home-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 256Mi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
